### ISSUE TITLE
"Unmaintained" Status?

### ISSUE THREAD

**Issue by drober76** [EndlesNights/ambientdoors#20]
Hi, Foundry is giving me a warning that Ambient Doors is "unmaintained," likely because it hasn't been updated in 8 months.  Is this because it simply works and doesn't need updating, or because it is inactive?  Specifically, will be it updated or needed in v10?

**Comment by EndlesNights** [comment]
It's probably because I haven't push any updates recently because everything still works as of a test on a brand new world I a few weeks back. (I just haven't kept up with the most recent version numbers). 
I did get pinged the other day on the main Foundry Discord because someone was having some issues, but I was unable to reproduce any of them, and they never got back to me when I offered them some suggestions for resetting their default settings.
